require_relative "master_check"

# Each new term in the Fibonacci sequence is
# generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence
# whose values do not exceed four million, find the
# sum of the even-valued terms.

def fib(first, second)
  temp_sum = first + second
  @sum += temp_sum if (temp_sum % 2).zero?
  first = second
  second = temp_sum

  fib(first, second) if temp_sum < 4000000
end

first = 0
second = 1
@sum = 0

fib(first, second)

master_check(@sum)

